<?php

namespace PFA\MaillingBundle\Repository;
use PFA\MainBundle\Entity\User;

/**
 * MailFolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailFolderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserFolders(User $user)
    {
        $query = $this->createQueryBuilder("f")
                ->where("f.owner = :owner")
                ->setParameter("owner", $user)
                ->andWhere("f.is_visible = :visible")
                ->setParameter("visible", true)
                ->getQuery();
        return $query->getResult();
    }
}
