<?php

namespace PFA\MaillingBundle\Repository;

/**
 * MailAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
