<?php

namespace PFA\MaillingBundle\Repository;

/**
 * MailFolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailFolderRepository extends \Doctrine\ORM\EntityRepository
{
}
