<?php

namespace PFA\MaillingBundle\Repository;

/**
 * MailBoxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailBoxRepository extends \Doctrine\ORM\EntityRepository
{
}
