<?php

namespace PFA\MaillingBundle\Repository;

/**
 * MailAttachementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailAttachementsRepository extends \Doctrine\ORM\EntityRepository
{
}
