<?php

namespace PFA\CoreBundle\Repository;

/**
 * ForumInteractionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumInteractionsRepository extends \Doctrine\ORM\EntityRepository
{
}
