<?php

namespace PFA\CoreBundle\Repository;

/**
 * ForumInterationAnwserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumInteractionAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
