<?php

namespace PFA\CoreBundle\Repository;
use PFA\CoreBundle\Entity\Project;

/**
 * ProjectMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectMemberRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjectMembers(Project $project)
    {
        $query = $this->createQueryBuilder("p")
            ->innerJoin("p.project", "project")
            ->where("project = :p")
            ->setParameter("p", $project);
        return $query->getQuery()->getResult();
    }
}
