<?php

namespace PFA\CoreBundle\Repository;

/**
 * ProjectModeratorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectModeratorRepository extends \Doctrine\ORM\EntityRepository
{
}
