<?php

namespace PFA\CoreBundle\Repository;
use PFA\MainBundle\Entity\User;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserProjects(User $user)
    {
        $q = $this->createQueryBuilder("p")
            ->join("p.members","members")
            ->join("members.memeber", "u")
            ->where("u = :u")
            ->setParameter("u", $user);
        
        return $q->getQuery()->getResult();
    }
}
