<?php

namespace PFA\CoreBundle\Repository;

/**
 * ShareZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareZoneRepository extends \Doctrine\ORM\EntityRepository
{
}
