<?php

namespace PFA\MainBundle\Repository;

/**
 * CalenderEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalenderEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
