<?php

namespace PFA\MainBundle\Repository;

/**
 * ChatRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
