<?php

namespace PFA\MainBundle\Repository;

/**
 * ChatRoomMessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatRoomMessagesRepository extends \Doctrine\ORM\EntityRepository
{
}
