<?php

namespace PFA\MainBundle\Repository;

/**
 * MessageAttachmentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageAttachmentsRepository extends \Doctrine\ORM\EntityRepository
{
}
