services:
#    pfa_mailling.example:
#        class: PFA\MaillingBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    pfa_mailling.managers.mail_folder_manager:
        class: PFA\MaillingBundle\Managers\MailFolderManager
        arguments:
            entityManager: '@doctrine.orm.entity_manager'

    pfa_mailling.managers.mail_box_manager:
          class: PFA\MaillingBundle\Managers\MailBoxManager
          arguments: ['@doctrine.orm.entity_manager']