pfa_rpc_main_test:
    channel: rpctest/{method}
    handler:
        callback: 'pfa.main.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+" #accept all valid regex, don't put delimiters !

pfa_chatroom_topic:
  channel: project/{id}/chat
  handler:
    callback: 'pfa.chatroom.topic'
  requirements:
    id:
      pattern: "\d+"

pfa_private_chat_topic:
  channel: project/{id}/private_chat/{user_1}/{user_2}
  handler:
    callback: 'pfa.chatroom.topic'
  requirements:
    id:
      pattern: "\d+"
    user_1:
      pattern: "\d+"
    user_2:
      pattern: "\d+"