pfa_core:
    resource: "@PFACoreBundle/Controller/"
    type:     annotation
    prefix:   /

pfa_mailling:
    resource: "@PFAMaillingBundle/Controller/"
    type:     annotation
    prefix:   /mailbox

pfa_main:
    resource: "@PFAMainBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"