<?php

namespace PFA\MainBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Ivory\CKEditorBundle\Form\Type\CKEditorType;

class UserType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            //->add('test',CKEditorType::class, array("mapped" => false))
            ->add("nom",null, array(
                "required" => true
            ))
            ->add("prenom")
            ->add("tel")
            ->add("email",EmailType::class, array(
                "attr" => array(
                    "autocomplete" => "off"
                )
            ))
            ->add("genre",ChoiceType::class, array(
                "choices" => array("H" => "Homme", "F" => "Femme")
            ))
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'PFA\MainBundle\Entity\User',
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        //return "user";
        return $this->getBlockPrefix();
    }

    /**
     * @return string
     */
    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType'; // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'app_user_registration';
    }
}
