services:
#    pfa_main.example:
#        class: PFA\MainBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    pfa.main_rpc.service:
        class: PFA\MainBundle\RPC\PFAMainRPC
        tags:
            - { name: gos_web_socket.rpc }

    pfa_main.form.registration:
        class: PFA\MainBundle\Form\UserType
        tags:
            - { name: form.type, alias: app_user_registration }