services:
#    pfa_main.example:
#        class: PFA\MainBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    pfa.main_rpc.service:
        class: PFA\MainBundle\RPC\PFAMainRPC
        arguments: ['@doctrine.orm.entity_manager', '@security.token_storage', '@gos_web_socket.websocket.client_manipulator']
        tags:
            - { name: gos_web_socket.rpc }

    pfa_main.form.registration:
        class: PFA\MainBundle\Form\UserType
        tags:
            - { name: form.type, alias: app_user_registration }

    pfa_main.topics.chat_room_topic:
        class: PFA\MainBundle\Topics\ChatRoomTopic
        arguments: ['@gos_web_socket.websocket.client_manipulator', '@gos_web_socket.client_storage', '@doctrine.orm.entity_manager']
        tags:
          - { name: gos_web_socket.topic }

    pfa_main.topics.private_chat_topic:
        class: PFA\MainBundle\Topics\PrivateChatTopic
        arguments: ['@gos_web_socket.websocket.client_manipulator', '@gos_web_socket.client_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: gos_web_socket.topic }

    pfa_core.managers.forum_manager:
        class: PFA\CoreBundle\Managers\ForumManager
        arguments: ['@doctrine.orm.entity_manager']